version: '3'

services:
  web:
    build: ./flask
    image: nedm0r/dockerflask
    ports:
      - "5005:5000"
    depends_on:
      - db
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_HOST=db
      - MYSQL_DATABASE=flask_db
    restart: always
  db:
    build: ./Mysql
    image: nedm0r/dockerdb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: