apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app-deployment
spec:
  replicas: 3  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
        - name: my-flask-app-container
          image: {{ .Values.myFlaskApp.image.repository }}:{{ .Values.myFlaskApp.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_USER
              value: root
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_DATABASE
              value: flask_db  
            - name: MYSQL_ROOT_PASSWORD
              value: password  
