apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app-deployment
spec:
  replicas: {{ .Values.myFlaskApp.replicaCount }}
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app-container
        image: {{ .Values.myFlaskApp.image.repository }}:{{ .Values.myFlaskApp.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: MYSQL_PASSWORD
            value: {{ .Values.myFlaskApp.env.MYSQL_PASSWORD }}
          - name: MYSQL_USER
            value: {{ .Values.myFlaskApp.env.MYSQL_USER }}
          - name: MYSQL_HOST
            value: {{ .Values.myFlaskApp.env.MYSQL_HOST }}
          - name: MYSQL_DATABASE
            value: {{ .Values.myFlaskApp.env.MYSQL_DATABASE }}
